### ISSUE TITLE
Add Dependabot to keep Rubygem dependencies up to date

### ISSUE THREAD

**Issue by veganstraightedge** [microformats/microformats-parser-website-ruby#58]
https://dependabot.com

Especially for security alerts: https://github.com/microformats/microformats-parser-website-ruby/network/alerts

**Comment by jgarber623** [comment]
Looks like this was completed based on [the PRs opened by dependabot](https://github.com/microformats/microformats-parser-website-ruby/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+). 🎉
